### ISSUE TITLE
Screenshot?

### ISSUE THREAD

**Issue by melodykramer** [BBC-News-Labs/election-2015-issues#1]
I was wondering if you could display a screenshot or indicate how this works. Would love to see, and am not on the BBC network :)

Mel

**Comment by iaincollins** [comment]
For sure! We really should do that for all our projects, especially the ones we end up not being confident to post visualisations of - have now added one to the repo and embedded it in the README.

https://github.com/BBC-News-Labs/election-2015-issues/blob/master/README.md
